### ISSUE TITLE
Can not log in the website to see demo

### ISSUE THREAD

**Issue by peterlee909** [EnigmaSoft/CMS#1]
Sorry, I can't log in with the provided username and password.
How could I do?
Thanks

**Comment by snopboy** [comment]
> 
> 
> Sorry, I can't log in with the provided username and password.
> How could I do?
> Thanks

You cannot log in with the provided credentials on a local setup of the website, these credentials are valid for Demo version only.
You can access the demo, log in and basically check it out as much as you want. Demo has been brought back online.
Demo: [Click here](https://enigmacms.000webhostapp.com/).

If you wish to create a new account on your local setup of Enigma, press the Register/Sign Up button on the navigation, then follow the registration process, your account should be successfully created within a few seconds.
